### ISSUE TITLE
Error editting hosts

### ISSUE THREAD

**Issue by JustDevNull** [AsydSolutions/ASYD#115] opened 2016-03-07 13:08 UTC
Every time I need to modify the IP address of a host I receive this message:

UNIQUE constraint failed: hosts.hostname

Looking at the log I can't see nothing wrong:

127.0.0.1 - - [07/Mar/2016:13:57:03 +0100] "GET /api/ping HTTP/1.1" 200 4 0.0027
127.0.0.1 - - [07/Mar/2016:13:57:15 +0100] "GET /api/ping HTTP/1.1" 200 4 0.0021
192.168.1.100 - - [07/Mar/2016:13:57:17 +0100] "GET /host/asia-haproxy HTTP/1.1" 200 14009 1.1318
127.0.0.1 - - [07/Mar/2016:13:57:24 +0100] "GET /api/ping HTTP/1.1" 200 4 0.0035
192.168.1.100 - - [07/Mar/2016:13:57:27 +0100] "POST /host/edit HTTP/1.1" 303 - 0.0207
192.168.1.100 - - [07/Mar/2016:13:57:31 +0100] "GET /host/asia-haproxy HTTP/1.1" 200 14091 3.2791
127.0.0.1 - - [07/Mar/2016:13:57:35 +0100] "GET /api/ping HTTP/1.1" 200 4 0.0035
127.0.0.1 - - [07/Mar/2016:13:57:46 +0100] "GET /api/ping HTTP/1.1" 200 4 0.0029

Can you check it please?

Thanks in advance.

**Comment by JustDevZero** [comment] 2016-03-07 22:55
I already talk about this with @Choms in our last meeting the problem is not visible in the logs, but the problem comes in the POST /host/edit HTTP/1.1". It's a bug in the route and must be fixed soon.

**Comment by Choms** [comment] 2016-05-02 15:58
Fixed in devel, sorry for the delay

**Closed by Choms** 2016-05-02 15:58 UTC
Labels: bug
